I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 36, in script
    while not name:
  File "game/script.rpy", line 36, in <module>
    while not name:
NameError: name 'name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 36, in script
    while not name:
  File "C:\Users\User\Desktop\renpy-8.0.1-sdk\renpy\ast.py", line 2058, in execute
    if renpy.python.py_eval(self.condition):
  File "C:\Users\User\Desktop\renpy-8.0.1-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\User\Desktop\renpy-8.0.1-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 36, in <module>
    while not name:
NameError: name 'name' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Simmer 1.0
Sun Jan 21 10:55:44 2024
